//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorQuiz.FrontEnd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorQuiz.FrontEnd.Resources.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        public static string Correct_answer {
            get {
                return ResourceManager.GetString("Correct answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam access code.
        /// </summary>
        public static string Exam_access_code {
            get {
                return ResourceManager.GetString("Exam access code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your exam code is invalid.
        /// </summary>
        public static string exam_code_invalid {
            get {
                return ResourceManager.GetString("exam-code-invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam is loading, please wait....
        /// </summary>
        public static string Exam_is_loading__please_wait___ {
            get {
                return ResourceManager.GetString("Exam is loading, please wait...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Results.
        /// </summary>
        public static string Exam_Results {
            get {
                return ResourceManager.GetString("Exam Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed questions.
        /// </summary>
        public static string Failed_questions {
            get {
                return ResourceManager.GetString("Failed questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next question.
        /// </summary>
        public static string Next_question {
            get {
                return ResourceManager.GetString("Next question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Exam.
        /// </summary>
        public static string Start_Exam {
            get {
                return ResourceManager.GetString("Start Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the exam.
        /// </summary>
        public static string Start_the_exam {
            get {
                return ResourceManager.GetString("Start the exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        public static string Time_Remaining {
            get {
                return ResourceManager.GetString("Time Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer.
        /// </summary>
        public static string Your_answer {
            get {
                return ResourceManager.GetString("Your answer", resourceCulture);
            }
        }
    }
}
